-- 09/06/2024 06:06 PM
--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apps_common_utils_requestlog; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_common_utils_requestlog (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    requests jsonb,
    CONSTRAINT apps_common_utils_requestlog_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_common_utils_requestlog OWNER TO app_core;

--
-- Name: apps_common_utils_requestlog_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_common_utils_requestlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_common_utils_requestlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_author; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_author (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    name character varying(250) NOT NULL,
    CONSTRAINT apps_project_author_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_author OWNER TO app_core;

--
-- Name: apps_project_author_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_book; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_book (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    title character varying(255) NOT NULL,
    publication_date date,
    is_available boolean NOT NULL,
    CONSTRAINT apps_project_book_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_book OWNER TO app_core;

--
-- Name: apps_project_book_author; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_book_author (
    id bigint NOT NULL,
    bookmodel_id bigint NOT NULL,
    authormodel_id bigint NOT NULL
);


ALTER TABLE public.apps_project_book_author OWNER TO app_core;

--
-- Name: apps_project_book_author_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_book_author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_book_author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_book_genre; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_book_genre (
    id bigint NOT NULL,
    bookmodel_id bigint NOT NULL,
    genremodel_id bigint NOT NULL
);


ALTER TABLE public.apps_project_book_genre OWNER TO app_core;

--
-- Name: apps_project_book_genre_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_book_genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_book_genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_book_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_career; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_career (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    name character varying(100) NOT NULL,
    CONSTRAINT apps_project_career_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_career OWNER TO app_core;

--
-- Name: apps_project_career_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_career ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_career_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_common_user; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_common_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    id uuid NOT NULL,
    is_teacher boolean NOT NULL,
    is_student boolean NOT NULL,
    identification_card character varying(100) NOT NULL,
    cell_phone character varying(15),
    birthday date,
    address text,
    career_id bigint,
    department_id bigint,
    CONSTRAINT apps_project_common_user_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_common_user OWNER TO app_core;

--
-- Name: apps_project_common_user_groups; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_common_user_groups (
    id bigint NOT NULL,
    usermodel_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.apps_project_common_user_groups OWNER TO app_core;

--
-- Name: apps_project_common_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_common_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_common_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_common_user_user_permissions; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_common_user_user_permissions (
    id bigint NOT NULL,
    usermodel_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.apps_project_common_user_user_permissions OWNER TO app_core;

--
-- Name: apps_project_common_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_common_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_common_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_department; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_department (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    name character varying(100) NOT NULL,
    CONSTRAINT apps_project_department_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_department OWNER TO app_core;

--
-- Name: apps_project_department_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_fine; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_fine (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    date date NOT NULL,
    amount numeric(10,2) NOT NULL,
    paid boolean NOT NULL,
    return_date date,
    loan_id bigint NOT NULL,
    CONSTRAINT apps_project_fine_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_fine OWNER TO app_core;

--
-- Name: apps_project_fine_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_fine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_fine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_genre; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_genre (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    name character varying(100) NOT NULL,
    CONSTRAINT apps_project_genre_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_genre OWNER TO app_core;

--
-- Name: apps_project_genre_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_library_staff; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_library_staff (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    is_chief_librarian boolean NOT NULL,
    department_id bigint,
    superior_id bigint,
    user_id uuid NOT NULL,
    CONSTRAINT apps_project_library_staff_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_library_staff OWNER TO app_core;

--
-- Name: apps_project_library_staff_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_library_staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_library_staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_loan; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_loan (
    id bigint NOT NULL,
    language character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    default_order integer,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status character varying(20) NOT NULL,
    return_date date,
    user_id uuid NOT NULL,
    CONSTRAINT apps_project_loan_default_order_check CHECK ((default_order >= 0))
);


ALTER TABLE public.apps_project_loan OWNER TO app_core;

--
-- Name: apps_project_loan_book; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.apps_project_loan_book (
    id bigint NOT NULL,
    loanmodel_id bigint NOT NULL,
    bookmodel_id bigint NOT NULL
);


ALTER TABLE public.apps_project_loan_book OWNER TO app_core;

--
-- Name: apps_project_loan_book_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_loan_book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_loan_book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_project_loan_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.apps_project_loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_project_loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditlog_logentry; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.auditlog_logentry (
    id integer NOT NULL,
    object_pk character varying(255) NOT NULL,
    object_id bigint,
    object_repr text NOT NULL,
    action smallint NOT NULL,
    changes text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    actor_id uuid,
    content_type_id integer NOT NULL,
    remote_addr inet,
    additional_data jsonb,
    serialized_data jsonb,
    CONSTRAINT auditlog_logentry_action_check CHECK ((action >= 0))
);


ALTER TABLE public.auditlog_logentry OWNER TO app_core;

--
-- Name: auditlog_logentry_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.auditlog_logentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditlog_logentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO app_core;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO app_core;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO app_core;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO app_core;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO app_core;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO app_core;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO app_core;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO app_core;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: app_core
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO app_core;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: app_core
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps_common_utils_requestlog apps_common_utils_requestlog_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_common_utils_requestlog
    ADD CONSTRAINT apps_common_utils_requestlog_pkey PRIMARY KEY (id);


--
-- Name: apps_project_author apps_project_author_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_author
    ADD CONSTRAINT apps_project_author_pkey PRIMARY KEY (id);


--
-- Name: apps_project_book_author apps_project_book_author_bookmodel_id_authormodel_2484e8b9_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_author
    ADD CONSTRAINT apps_project_book_author_bookmodel_id_authormodel_2484e8b9_uniq UNIQUE (bookmodel_id, authormodel_id);


--
-- Name: apps_project_book_author apps_project_book_author_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_author
    ADD CONSTRAINT apps_project_book_author_pkey PRIMARY KEY (id);


--
-- Name: apps_project_book_genre apps_project_book_genre_bookmodel_id_genremodel__100fb82e_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_genre
    ADD CONSTRAINT apps_project_book_genre_bookmodel_id_genremodel__100fb82e_uniq UNIQUE (bookmodel_id, genremodel_id);


--
-- Name: apps_project_book_genre apps_project_book_genre_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_genre
    ADD CONSTRAINT apps_project_book_genre_pkey PRIMARY KEY (id);


--
-- Name: apps_project_book apps_project_book_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book
    ADD CONSTRAINT apps_project_book_pkey PRIMARY KEY (id);


--
-- Name: apps_project_career apps_project_career_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_career
    ADD CONSTRAINT apps_project_career_pkey PRIMARY KEY (id);


--
-- Name: apps_project_common_user_groups apps_project_common_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_groups
    ADD CONSTRAINT apps_project_common_user_groups_pkey PRIMARY KEY (id);


--
-- Name: apps_project_common_user apps_project_common_user_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user
    ADD CONSTRAINT apps_project_common_user_pkey PRIMARY KEY (id);


--
-- Name: apps_project_common_user_user_permissions apps_project_common_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_user_permissions
    ADD CONSTRAINT apps_project_common_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: apps_project_common_user_groups apps_project_common_user_usermodel_id_group_id_d9917839_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_groups
    ADD CONSTRAINT apps_project_common_user_usermodel_id_group_id_d9917839_uniq UNIQUE (usermodel_id, group_id);


--
-- Name: apps_project_common_user_user_permissions apps_project_common_user_usermodel_id_permission__0fd1abb8_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_user_permissions
    ADD CONSTRAINT apps_project_common_user_usermodel_id_permission__0fd1abb8_uniq UNIQUE (usermodel_id, permission_id);


--
-- Name: apps_project_common_user apps_project_common_user_username_key; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user
    ADD CONSTRAINT apps_project_common_user_username_key UNIQUE (username);


--
-- Name: apps_project_department apps_project_department_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_department
    ADD CONSTRAINT apps_project_department_pkey PRIMARY KEY (id);


--
-- Name: apps_project_fine apps_project_fine_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_fine
    ADD CONSTRAINT apps_project_fine_pkey PRIMARY KEY (id);


--
-- Name: apps_project_genre apps_project_genre_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_genre
    ADD CONSTRAINT apps_project_genre_pkey PRIMARY KEY (id);


--
-- Name: apps_project_library_staff apps_project_library_staff_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_library_staff
    ADD CONSTRAINT apps_project_library_staff_pkey PRIMARY KEY (id);


--
-- Name: apps_project_library_staff apps_project_library_staff_user_id_key; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_library_staff
    ADD CONSTRAINT apps_project_library_staff_user_id_key UNIQUE (user_id);


--
-- Name: apps_project_loan_book apps_project_loan_book_loanmodel_id_bookmodel_id_a870d760_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_loan_book
    ADD CONSTRAINT apps_project_loan_book_loanmodel_id_bookmodel_id_a870d760_uniq UNIQUE (loanmodel_id, bookmodel_id);


--
-- Name: apps_project_loan_book apps_project_loan_book_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_loan_book
    ADD CONSTRAINT apps_project_loan_book_pkey PRIMARY KEY (id);


--
-- Name: apps_project_loan apps_project_loan_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_loan
    ADD CONSTRAINT apps_project_loan_pkey PRIMARY KEY (id);


--
-- Name: auditlog_logentry auditlog_logentry_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auditlog_logentry
    ADD CONSTRAINT auditlog_logentry_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: apps_project_book_author_authormodel_id_3a8d94ff; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_book_author_authormodel_id_3a8d94ff ON public.apps_project_book_author USING btree (authormodel_id);


--
-- Name: apps_project_book_author_bookmodel_id_b1143232; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_book_author_bookmodel_id_b1143232 ON public.apps_project_book_author USING btree (bookmodel_id);


--
-- Name: apps_project_book_genre_bookmodel_id_45a0b91a; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_book_genre_bookmodel_id_45a0b91a ON public.apps_project_book_genre USING btree (bookmodel_id);


--
-- Name: apps_project_book_genre_genremodel_id_f12182b8; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_book_genre_genremodel_id_f12182b8 ON public.apps_project_book_genre USING btree (genremodel_id);


--
-- Name: apps_project_common_user_career_id_c55dcec3; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_common_user_career_id_c55dcec3 ON public.apps_project_common_user USING btree (career_id);


--
-- Name: apps_project_common_user_department_id_267d51f9; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_common_user_department_id_267d51f9 ON public.apps_project_common_user USING btree (department_id);


--
-- Name: apps_project_common_user_groups_group_id_d3318472; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_common_user_groups_group_id_d3318472 ON public.apps_project_common_user_groups USING btree (group_id);


--
-- Name: apps_project_common_user_groups_usermodel_id_bc9a3aa3; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_common_user_groups_usermodel_id_bc9a3aa3 ON public.apps_project_common_user_groups USING btree (usermodel_id);


--
-- Name: apps_project_common_user_u_permission_id_1c1475e8; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_common_user_u_permission_id_1c1475e8 ON public.apps_project_common_user_user_permissions USING btree (permission_id);


--
-- Name: apps_project_common_user_user_permissions_usermodel_id_f8afa62d; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_common_user_user_permissions_usermodel_id_f8afa62d ON public.apps_project_common_user_user_permissions USING btree (usermodel_id);


--
-- Name: apps_project_common_user_username_5d7ccc58_like; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_common_user_username_5d7ccc58_like ON public.apps_project_common_user USING btree (username varchar_pattern_ops);


--
-- Name: apps_project_fine_loan_id_fd034dd0; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_fine_loan_id_fd034dd0 ON public.apps_project_fine USING btree (loan_id);


--
-- Name: apps_project_library_staff_department_id_3f93b5b7; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_library_staff_department_id_3f93b5b7 ON public.apps_project_library_staff USING btree (department_id);


--
-- Name: apps_project_library_staff_superior_id_1f711d50; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_library_staff_superior_id_1f711d50 ON public.apps_project_library_staff USING btree (superior_id);


--
-- Name: apps_project_loan_book_bookmodel_id_84628974; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_loan_book_bookmodel_id_84628974 ON public.apps_project_loan_book USING btree (bookmodel_id);


--
-- Name: apps_project_loan_book_loanmodel_id_bfcc5d15; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_loan_book_loanmodel_id_bfcc5d15 ON public.apps_project_loan_book USING btree (loanmodel_id);


--
-- Name: apps_project_loan_user_id_800494a6; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX apps_project_loan_user_id_800494a6 ON public.apps_project_loan USING btree (user_id);


--
-- Name: auditlog_logentry_action_229afe39; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auditlog_logentry_action_229afe39 ON public.auditlog_logentry USING btree (action);


--
-- Name: auditlog_logentry_actor_id_959271d2; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auditlog_logentry_actor_id_959271d2 ON public.auditlog_logentry USING btree (actor_id);


--
-- Name: auditlog_logentry_content_type_id_75830218; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auditlog_logentry_content_type_id_75830218 ON public.auditlog_logentry USING btree (content_type_id);


--
-- Name: auditlog_logentry_object_id_09c2eee8; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auditlog_logentry_object_id_09c2eee8 ON public.auditlog_logentry USING btree (object_id);


--
-- Name: auditlog_logentry_object_pk_6e3219c0; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auditlog_logentry_object_pk_6e3219c0 ON public.auditlog_logentry USING btree (object_pk);


--
-- Name: auditlog_logentry_object_pk_6e3219c0_like; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auditlog_logentry_object_pk_6e3219c0_like ON public.auditlog_logentry USING btree (object_pk varchar_pattern_ops);


--
-- Name: auditlog_logentry_timestamp_37867bb0; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auditlog_logentry_timestamp_37867bb0 ON public.auditlog_logentry USING btree ("timestamp");


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: app_core
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: apps_project_book_author apps_project_book_au_authormodel_id_3a8d94ff_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_author
    ADD CONSTRAINT apps_project_book_au_authormodel_id_3a8d94ff_fk_apps_proj FOREIGN KEY (authormodel_id) REFERENCES public.apps_project_author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_book_author apps_project_book_au_bookmodel_id_b1143232_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_author
    ADD CONSTRAINT apps_project_book_au_bookmodel_id_b1143232_fk_apps_proj FOREIGN KEY (bookmodel_id) REFERENCES public.apps_project_book(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_book_genre apps_project_book_ge_bookmodel_id_45a0b91a_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_genre
    ADD CONSTRAINT apps_project_book_ge_bookmodel_id_45a0b91a_fk_apps_proj FOREIGN KEY (bookmodel_id) REFERENCES public.apps_project_book(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_book_genre apps_project_book_ge_genremodel_id_f12182b8_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_book_genre
    ADD CONSTRAINT apps_project_book_ge_genremodel_id_f12182b8_fk_apps_proj FOREIGN KEY (genremodel_id) REFERENCES public.apps_project_genre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_common_user apps_project_common__career_id_c55dcec3_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user
    ADD CONSTRAINT apps_project_common__career_id_c55dcec3_fk_apps_proj FOREIGN KEY (career_id) REFERENCES public.apps_project_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_common_user apps_project_common__department_id_267d51f9_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user
    ADD CONSTRAINT apps_project_common__department_id_267d51f9_fk_apps_proj FOREIGN KEY (department_id) REFERENCES public.apps_project_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_common_user_groups apps_project_common__group_id_d3318472_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_groups
    ADD CONSTRAINT apps_project_common__group_id_d3318472_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_common_user_user_permissions apps_project_common__permission_id_1c1475e8_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_user_permissions
    ADD CONSTRAINT apps_project_common__permission_id_1c1475e8_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_common_user_groups apps_project_common__usermodel_id_bc9a3aa3_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_groups
    ADD CONSTRAINT apps_project_common__usermodel_id_bc9a3aa3_fk_apps_proj FOREIGN KEY (usermodel_id) REFERENCES public.apps_project_common_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_common_user_user_permissions apps_project_common__usermodel_id_f8afa62d_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_common_user_user_permissions
    ADD CONSTRAINT apps_project_common__usermodel_id_f8afa62d_fk_apps_proj FOREIGN KEY (usermodel_id) REFERENCES public.apps_project_common_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_fine apps_project_fine_loan_id_fd034dd0_fk_apps_project_loan_id; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_fine
    ADD CONSTRAINT apps_project_fine_loan_id_fd034dd0_fk_apps_project_loan_id FOREIGN KEY (loan_id) REFERENCES public.apps_project_loan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_library_staff apps_project_library_department_id_3f93b5b7_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_library_staff
    ADD CONSTRAINT apps_project_library_department_id_3f93b5b7_fk_apps_proj FOREIGN KEY (department_id) REFERENCES public.apps_project_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_library_staff apps_project_library_superior_id_1f711d50_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_library_staff
    ADD CONSTRAINT apps_project_library_superior_id_1f711d50_fk_apps_proj FOREIGN KEY (superior_id) REFERENCES public.apps_project_library_staff(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_library_staff apps_project_library_user_id_b649b448_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_library_staff
    ADD CONSTRAINT apps_project_library_user_id_b649b448_fk_apps_proj FOREIGN KEY (user_id) REFERENCES public.apps_project_common_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_loan_book apps_project_loan_bo_bookmodel_id_84628974_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_loan_book
    ADD CONSTRAINT apps_project_loan_bo_bookmodel_id_84628974_fk_apps_proj FOREIGN KEY (bookmodel_id) REFERENCES public.apps_project_book(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_loan_book apps_project_loan_bo_loanmodel_id_bfcc5d15_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_loan_book
    ADD CONSTRAINT apps_project_loan_bo_loanmodel_id_bfcc5d15_fk_apps_proj FOREIGN KEY (loanmodel_id) REFERENCES public.apps_project_loan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apps_project_loan apps_project_loan_user_id_800494a6_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.apps_project_loan
    ADD CONSTRAINT apps_project_loan_user_id_800494a6_fk_apps_proj FOREIGN KEY (user_id) REFERENCES public.apps_project_common_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auditlog_logentry auditlog_logentry_actor_id_959271d2_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auditlog_logentry
    ADD CONSTRAINT auditlog_logentry_actor_id_959271d2_fk_apps_proj FOREIGN KEY (actor_id) REFERENCES public.apps_project_common_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auditlog_logentry auditlog_logentry_content_type_id_75830218_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auditlog_logentry
    ADD CONSTRAINT auditlog_logentry_content_type_id_75830218_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_apps_project_common_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_apps_project_common_user_id FOREIGN KEY (user_id) REFERENCES public.apps_project_common_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_apps_proj; Type: FK CONSTRAINT; Schema: public; Owner: app_core
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_apps_proj FOREIGN KEY (user_id) REFERENCES public.apps_project_common_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

